### ISSUE TITLE
Test create release

### ISSUE THREAD

**Issue by moha-b** [moha-b/workflows#3]

**Comment by moha-b** [comment]
the workflow works fine but the issue within the path

```yaml
    - name: Build APK
      run: flutter build apk --release --split-per-abi

    - name: Get Project Name
      id: get_project_name
      run: echo "::set-output name=name::$(awk '/name:/ {print $2}' pubspec.yaml | sed 's/ //g')"

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ steps.get_project_name.outputs.name }} ${{ github.ref }}
        body: |
          Changes in this release:
          - Add APK for Android.

    - name: Upload APK to Release
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: build/app/outputs/apk/release/*
        asset_name: app-release-${{ github.sha }}.apk
        asset_content_type: application/vnd.android.package-archive
```
### So where is the issue 

- the first thing it creates an `APK` successfully, **but doesn't create a build folder**
- the second command is getting the project name to make it the release name
- third, it creates a release
- finally, it uploads the `APK` from this path ` build/app/outputs/apk/release/*` so this folder didn't exist so if you need this `workflow` to work as you expect you have to build the app every time u made changes then create a release with this command 
```shell
git tag -a v0.0.1 -m'testing release action'
git push origin v0.0.1
```
